version: "3"
services:
  app:
    image: "mcmafia"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcmafia-dev-container
    restart: unless-stopped
    ports:
      - ${PORT}:8000
    volumes:
      - ./app:/app/app
    env_file:
      - .env